### ISSUE TITLE
No indexes found on #{table_name} with the options provided.

### ISSUE THREAD

**Issue by DismalShadowX** [DismalShadowX/project-tracker#4]
Ruuning `RAILS_ENV=production bundle exec rails db:migrate` causes an `No indexes found on #{table_name} with the options provided.` error.

This is from upstream `main` branch from the official Mastodon repo as of 10/29/2024 build (4.4-alpha.1)

```
Bundle complete! 147 Gemfile dependencies, 277 gems now installed.
Gems in the groups 'development' and 'test' were not installed.
Bundled gems are installed into `./vendor/bundle`
mastodon@Nexus-OS:~/live$ RAILS_ENV=production bundle exec rails db:migrate
I, [2024-10-29T09:05:33.331592 #1242958]  INFO -- : [dotenv] Loaded .env.production
I, [2024-10-29T09:05:34.793294 #1242958]  INFO -- : Migrating to RemoveDuplicateIndexes (20241014010506)
== 20241014010506 RemoveDuplicateIndexes: migrating ===========================
[strong_migrations] DANGER: No lock timeout set
-- remove_index(:account_aliases, :account_id)
bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

No indexes found on account_aliases with the options provided.
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:1637:in `index_name_for_remove'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:505:in `remove_index'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration/default_strategy.rb:10:in `method_missing'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1047:in `block in method_missing'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1017:in `block in say_with_time'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1017:in `say_with_time'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1036:in `method_missing'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/migration.rb:17:in `block (2 levels) in method_missing'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/checker.rb:101:in `perform'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/migration.rb:16:in `block in method_missing'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/migration.rb:15:in `catch'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/migration.rb:15:in `method_missing'
/home/mastodon/live/db/migrate/20241014010506_remove_duplicate_indexes.rb:5:in `change'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:986:in `exec_migration'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:970:in `block (2 levels) in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:969:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:227:in `with_connection'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:968:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/migration.rb:5:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy/railtie.rb:28:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy/strategy.rb:60:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy.rb:151:in `strategy'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy/railtie.rb:28:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1178:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1529:in `block in execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1580:in `ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/migrator.rb:4:in `ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1528:in `execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1503:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1503:in `migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1448:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1600:in `with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1448:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy/railtie.rb:28:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy/strategy.rb:60:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy.rb:151:in `strategy'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy/railtie.rb:28:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1274:in `up'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1249:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/tasks/database_tasks.rb:251:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/database_tasks.rb:5:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/railties/databases.rake:93:in `block (2 levels) in <main>'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/commands/rake/rake_command.rb:27:in `block (2 levels) in perform'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/commands/rake/rake_command.rb:44:in `block in with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/command.rb:156:in `invoke_rake'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/command.rb:73:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/command.rb:149:in `with_argv'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/command.rb:69:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/commands.rb:18:in `<main>'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'

Caused by:
ArgumentError: No indexes found on account_aliases with the options provided. (ArgumentError)

            raise ArgumentError, "No indexes found on #{table_name} with the options provided."
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:1637:in `index_name_for_remove'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:505:in `remove_index'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration/default_strategy.rb:10:in `method_missing'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1047:in `block in method_missing'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1017:in `block in say_with_time'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1017:in `say_with_time'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1036:in `method_missing'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/migration.rb:17:in `block (2 levels) in method_missing'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/checker.rb:101:in `perform'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/migration.rb:16:in `block in method_missing'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/migration.rb:15:in `catch'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/migration.rb:15:in `method_missing'
/home/mastodon/live/db/migrate/20241014010506_remove_duplicate_indexes.rb:5:in `change'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:986:in `exec_migration'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:970:in `block (2 levels) in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:969:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:227:in `with_connection'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:968:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/migration.rb:5:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy/railtie.rb:28:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy/strategy.rb:60:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy.rb:151:in `strategy'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy/railtie.rb:28:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1178:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1529:in `block in execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.4.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1580:in `ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/migrator.rb:4:in `ddl_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1528:in `execute_migration_in_transaction'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1503:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1503:in `migrate_without_lock'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1448:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1600:in `with_advisory_lock'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1448:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy/railtie.rb:28:in `block in migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy/strategy.rb:60:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy.rb:151:in `strategy'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/chewy-7.6.0/lib/chewy/railtie.rb:28:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1274:in `up'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:1249:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/tasks/database_tasks.rb:251:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/database_tasks.rb:5:in `migrate'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.2/lib/active_record/railties/databases.rake:93:in `block (2 levels) in <main>'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/commands/rake/rake_command.rb:27:in `block (2 levels) in perform'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/commands/rake/rake_command.rb:44:in `block in with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/command.rb:156:in `invoke_rake'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/command.rb:73:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/command.rb:149:in `with_argv'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/command.rb:69:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.1.4.2/lib/rails/commands.rb:18:in `<main>'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
mastodon@Nexus-OS:~/live$
```

**Comment by DismalShadowX** [comment]
Fixed by running `INSERT INTO schema_migrations (version) values ('20241014010506');` manually im `dbconsole` like so `RAILS_ENV=production bin/rails dbconsole`
